DROP DATABASE IF EXISTS LIVESMART;
CREATE DATABASE LIVESMART;
USE LIVESMART;

DROP TABLE IF EXISTS USERS;
CREATE TABLE USERS(
	username VARCHAR(256) NOT NULL,
	password VARCHAR(256) NOT NULL,
	is_admin BOOLEAN DEFAULT FALSE,
	PRIMARY KEY (username)
);

DROP TABLE IF EXISTS USER_CARBON;
CREATE TABLE USER_CARBON(
	username VARCHAR(256) NOT NULL,
	carbon_level INT(10) NOT NULL,
	carbon_date DATE,
	FOREIGN KEY (username) REFERENCES USERS(username) ON DELETE CASCADE ON UPDATE CASCADE
);

DROP TABLE IF EXISTS GEN_STATS;
CREATE TABLE GEN_STATS(
	username VARCHAR(256) NOT NULL,
	age INT(2) NOT NULL,
	gender INT(2) NOT NULL,
	education INT(2) NOT NULL,
	salary INT(2) NOT NULL,
	score INT(2) NOT NULL,
	perception INT(2) NOT NULL,
	FOREIGN KEY (username) REFERENCES USERS(username) ON DELETE CASCADE ON UPDATE CASCADE,
	PRIMARY KEY (username)
);
