DROP DATABASE IF EXISTS LIVESMART;
CREATE DATABASE LIVESMART;
USE LIVESMART;

DROP TABLE IF EXISTS USERS;
CREATE TABLE USERS(
	username VARCHAR(256) NOT NULL,
	password VARCHAR(256) NOT NULL,
	is_admin BOOLEAN DEFAULT FALSE,
	PRIMARY KEY (username)
);